/**
 * Agent Company Server
 * Express + WebSocket for real-time agent pipeline visualization
 * Uses real Claude Code instances (`claude -p`) instead of API
 */
import express from 'express';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import {
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
  readdirSync,
} from 'fs';

import { MessageBus } from '../core/message-bus.js';
import { Pipeline } from '../core/pipeline.js';
import { ClaudeCLI } from '../core/claude-cli.js';
import { PMAgent } from '../agents/pm-agent.js';
import { ArchitectAgent } from '../agents/architect-agent.js';
import { DeveloperAgent } from '../agents/developer-agent.js';
import { ReviewerAgent } from '../agents/reviewer-agent.js';
import { TesterAgent } from '../agents/tester-agent.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, '../..');

const PORT = process.env.PORT || 3000;
const OUTPUT_BASE = join(PROJECT_ROOT, 'output');

mkdirSync(OUTPUT_BASE, { recursive: true });

// --- App Setup ---
const app = express();
const server = createServer(app);
const wss = new WebSocketServer({ server });

app.use(express.json());
app.use(express.static(join(__dirname, '../../public')));

// --- Event History (현재 세션용, 새로고침 복원) ---
let eventHistory = [];
const MAX_HISTORY = 500;
let sessionStartTime = null;

// --- WebSocket clients ---
const clients = new Set();

wss.on('connection', (ws) => {
  clients.add(ws);
  console.log(`Client connected (${clients.size} total)`);

  if (eventHistory.length > 0) {
    ws.send(JSON.stringify({
      event: 'restore',
      history: eventHistory,
      sessionStartTime,
      timestamp: new Date().toISOString(),
    }));
  }

  ws.on('close', () => {
    clients.delete(ws);
    console.log(`Client disconnected (${clients.size} total)`);
  });
});

function broadcastWs(data) {
  eventHistory.push(data);
  if (eventHistory.length > MAX_HISTORY) eventHistory.shift();

  const payload = JSON.stringify(data);
  for (const client of clients) {
    if (client.readyState === 1) client.send(payload);
  }
}

// ============================================
// REPORT.md 생성 (프로젝트 완료 시 output 폴더에 저장)
// ============================================

function generateReport(project, outputDir, elapsed) {
  const stages = project.stages || [];
  const reviewRounds = stages[3]?.reviewRounds || [];

  const lines = [
    `# ${project.idea}`,
    '',
    `> Generated by Agent Company | ${new Date(project.createdAt).toLocaleString('ko-KR')}`,
    `> 소요 시간: ${elapsed} | 상태: ${project.status}`,
    '',
    '---',
    '',
  ];

  const stageLabels = ['기획 (PM)', '설계 (Architect)', '개발 (Developer)', '리뷰 (Reviewer)', '테스트 (Tester)'];

  for (let i = 0; i < stages.length; i++) {
    const s = stages[i];
    lines.push(`## ${i + 1}. ${stageLabels[i]}`);
    lines.push('');

    if (s.output) {
      lines.push(s.output);
    } else {
      lines.push('*(출력 없음)*');
    }
    lines.push('');

    // 리뷰 라운드 정보
    if (i === 3 && reviewRounds.length > 0) {
      lines.push('### 리뷰 라운드');
      lines.push('');
      lines.push('| 라운드 | 점수 | 결과 |');
      lines.push('|--------|------|------|');
      for (const r of reviewRounds) {
        const passed = r.score >= 70 ? 'PASS' : 'FAIL';
        lines.push(`| ${r.round}차 | ${r.score}/100 | ${passed} |`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  const md = lines.join('\n');
  const reportPath = join(outputDir, 'REPORT.md');
  writeFileSync(reportPath, md, 'utf-8');
  console.log(`Report saved: ${reportPath}`);
}

// --- Agent System ---
const messageBus = new MessageBus();
let currentOutputDir = null;

function createPipeline(outputDir) {
  currentOutputDir = outputDir;
  mkdirSync(outputDir, { recursive: true });

  const makeCli = (agentId) =>
    new ClaudeCLI({
      workDir: outputDir,
      onEvent: (event) => {
        broadcastWs({
          event: 'agent_activity',
          agentId,
          activity: event,
          timestamp: new Date().toISOString(),
        });
      },
    });

  const agents = new Map();
  agents.set('pm', new PMAgent(makeCli('pm')));
  agents.set('architect', new ArchitectAgent(makeCli('architect')));
  agents.set('developer', new DeveloperAgent(makeCli('developer'), outputDir));
  agents.set('reviewer', new ReviewerAgent(makeCli('reviewer'), outputDir));
  agents.set('tester', new TesterAgent(makeCli('tester'), outputDir));

  return new Pipeline(messageBus, agents, (update) => {
    broadcastWs(update);

    if (update.event === 'project_completed' && update.project) {
      const elapsed = sessionStartTime
        ? `${Math.floor((Date.now() - sessionStartTime) / 1000)}s`
        : 'unknown';
      generateReport(update.project, outputDir, elapsed);
    }
  }, outputDir);
}

let activePipeline = null;

messageBus.subscribe('all', (message) => {
  broadcastWs({
    event: 'agent_message',
    message,
    timestamp: new Date().toISOString(),
  });
});

// --- API Routes ---

app.post('/api/projects', async (req, res) => {
  const { idea, workDir } = req.body;

  if (!idea || typeof idea !== 'string' || idea.trim().length === 0) {
    return res.status(400).json({ error: 'idea is required' });
  }

  // workDir이 지정되면 그 폴더에서 작업, 아니면 output/ 안에 자동 생성
  const outputDir = workDir
    ? workDir.trim()
    : join(OUTPUT_BASE, `project-${Date.now()}`);

  console.log(`Starting project in: ${outputDir}`);

  eventHistory = [];
  sessionStartTime = Date.now();

  activePipeline = createPipeline(outputDir);

  // UI에 작업 폴더 알림
  broadcastWs({
    event: 'work_dir',
    workDir: outputDir,
    timestamp: new Date().toISOString(),
  });

  res.json({
    message: 'Project pipeline started',
    idea: idea.trim(),
    outputDir,
  });

  try {
    await activePipeline.startProject(idea.trim());
  } catch (err) {
    console.error('Pipeline error:', err);
    broadcastWs({
      event: 'project_failed',
      error: err.message || String(err),
      timestamp: new Date().toISOString(),
    });
  }
});

// 프로젝트 중단
app.post('/api/projects/abort', (_req, res) => {
  if (!activePipeline) {
    return res.status(400).json({ error: 'No active pipeline' });
  }

  activePipeline.abort();

  broadcastWs({
    event: 'project_aborted',
    timestamp: new Date().toISOString(),
  });

  res.json({ message: 'Pipeline abort signal sent' });
});

// 실패한 프로젝트 재개 (checkpoint.json 기반)
app.post('/api/projects/resume/:name', async (req, res) => {
  const projectName = req.params.name;
  const outputDir = join(OUTPUT_BASE, projectName);
  const checkpoint = Pipeline.loadCheckpoint(outputDir);

  if (!checkpoint) {
    return res.status(404).json({ error: 'No checkpoint found for this project' });
  }

  eventHistory = [];
  sessionStartTime = Date.now();

  activePipeline = createPipeline(outputDir);

  const completedStages = checkpoint.stages
    .filter((s) => s.status === 'completed')
    .map((s) => s.label);

  res.json({
    message: 'Project resumed from checkpoint',
    idea: checkpoint.idea,
    projectName,
    completedStages,
  });

  try {
    await activePipeline.resumeProject(checkpoint);
  } catch (err) {
    console.error('Resume error:', err);
    broadcastWs({
      event: 'project_failed',
      error: err.message || String(err),
      timestamp: new Date().toISOString(),
    });
  }
});

// 이전 프로젝트 목록 (output/ 폴더의 REPORT.md 스캔)
app.get('/api/history', (_req, res) => {
  if (!existsSync(OUTPUT_BASE)) return res.json([]);

  const projects = readdirSync(OUTPUT_BASE, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      const dirPath = join(OUTPUT_BASE, d.name);
      const reportPath = join(dirPath, 'REPORT.md');
      const cpPath = join(dirPath, 'checkpoint.json');
      const hasCheckpoint = existsSync(cpPath);
      const hasReport = existsSync(reportPath);

      // checkpoint만 있고 report 없으면 = 실패한 프로젝트 (재개 가능)
      if (!hasReport && !hasCheckpoint) return null;

      let title = d.name;
      let status = 'unknown';
      let elapsed = '';

      if (hasReport) {
        const content = readFileSync(reportPath, 'utf-8');
        const titleMatch = content.match(/^#\s+(.+)$/m);
        title = titleMatch ? titleMatch[1] : d.name;
        const statusMatch = content.match(/상태:\s*(\w+)/);
        status = statusMatch ? statusMatch[1] : 'unknown';
        const timeMatch = content.match(/소요 시간:\s*([^\s|]+)/);
        elapsed = timeMatch ? timeMatch[1] : '';
      } else if (hasCheckpoint) {
        try {
          const cp = JSON.parse(readFileSync(cpPath, 'utf-8'));
          title = cp.idea || d.name;
          status = 'failed';
          const done = (cp.stages || []).filter((s) => s.status === 'completed').length;
          elapsed = `${done}/5 stages`;
        } catch { /* ignore */ }
      }

      return {
        name: d.name,
        title,
        status,
        elapsed,
        canResume: hasCheckpoint && status === 'failed',
      };
    })
    .filter(Boolean)
    .reverse(); // 최신 순

  res.json(projects);
});

// 특정 프로젝트의 REPORT.md 반환
app.get('/api/history/:name', (req, res) => {
  const reportPath = join(OUTPUT_BASE, req.params.name, 'REPORT.md');
  if (!existsSync(reportPath)) {
    return res.status(404).json({ error: 'Report not found' });
  }
  const content = readFileSync(reportPath, 'utf-8');
  res.json({ name: req.params.name, report: content });
});

app.get('/api/projects', (_req, res) => {
  if (!activePipeline) return res.json([]);
  res.json(activePipeline.getAllProjects());
});

app.get('/api/messages', (_req, res) => {
  res.json(messageBus.getAllMessages());
});

// output 폴더 목록 (작업 폴더 선택용)
app.get('/api/folders', (_req, res) => {
  if (!existsSync(OUTPUT_BASE)) return res.json([]);

  const folders = readdirSync(OUTPUT_BASE, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      const dirPath = join(OUTPUT_BASE, d.name);
      const hasCheckpoint = existsSync(join(dirPath, 'checkpoint.json'));
      const hasReport = existsSync(join(dirPath, 'REPORT.md'));
      return {
        name: d.name,
        path: dirPath,
        hasCheckpoint,
        hasReport,
      };
    })
    .reverse();

  res.json({ base: OUTPUT_BASE, folders });
});

app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', agents: 5, mode: 'claude-code', uptime: process.uptime() });
});

// --- Start ---
server.listen(PORT, () => {
  // 기존 프로젝트 수 카운트
  let savedCount = 0;
  if (existsSync(OUTPUT_BASE)) {
    savedCount = readdirSync(OUTPUT_BASE, { withFileTypes: true })
      .filter((d) => d.isDirectory() && existsSync(join(OUTPUT_BASE, d.name, 'REPORT.md')))
      .length;
  }

  console.log(`
  ╔══════════════════════════════════════════════╗
  ║       Agent Company v2.0.0                   ║
  ║       Powered by Claude Code                 ║
  ║                                              ║
  ║   PM        → 기획                            ║
  ║   Architect → 설계                            ║
  ║   Developer ⇄ Reviewer (피드백 루프)          ║
  ║   Tester    → 테스트 (실제 실행)              ║
  ║                                              ║
  ║   Review pass score: 70/100 (max 3 rounds)   ║
  ║                                              ║
  ║   Output: ./output/ (${savedCount} projects)        ║
  ║   http://localhost:${PORT}                      ║
  ╚══════════════════════════════════════════════╝
  `);
});
